version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "spark_db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./csv/:/var/lib/postgresql/docker-entrypoint-initdb.d/csv/
      - ./sql/:/docker-entrypoint-initdb.d/
    ports:
      - 5332:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    tty: true
  
  spark-master:
    image: docker.io/bitnami/spark:3.3
    restart: always
    depends_on:
      - postgres
    environment:
      - SPARK_MODE=master
      - SPARK_WORKER_INSTANCES=2
      - SPARK_WORKER_CORES=2
      - SPARK_MASTER_HOST=spark-master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED:=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - ./python_app/:/opt/bitnami/spark/python_app
      - ./driver/:/opt/bitnami/spark/driver/
    ports:
      - '8080:8080'
      - '7077:7077'
  
  spark-worker1:
    image: docker.io/bitnami/spark:3.3
    restart: always
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
  
  spark-worker2:
    image: docker.io/bitnami/spark:3.3
    restart: always
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark